apiVersion: v1
kind: Service
metadata:
  name: learning-devops
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # This is the port your service will expose
      targetPort: 80   # This is the port the container is listening on
  type: LoadBalancer

